@startuml
scale 1.5
caption Escala de tiempo en milisegundos (ms) - Diagrama de Tiempo - CU03: Gestionar Chat
robust "CU03 Gestionar Chat" as L0

@0.0
L0 is "Recibir Mensaje"
@0.2
L0 is "Guardar Historial BD"
@0.5
L0 is "Petición a IA"
@0.8
L0 is "Generando Respuesta LLM"
@25.0
L0 is "Procesar Respuesta"
@25.3
L0 is "Guardar Respuesta BD"
@25.7
L0 is "Retornar Chat Actualizado"
@26.5
L0 is "Retornar Chat Actualizado"
@enduml